export const appearAnimationOptions = [
    { value: 'none', name: 'None' },
    { value: 'fade-in', name: 'Fade In' },
    { value: 'fade-up-in', name: 'Fade Up' },
    { value: 'fade-down-in', name: 'Fade Down' },
    { value: 'fade-left-in', name: 'Fade Left' },
    { value: 'fade-right-in', name: 'Fade Right' },
    { value: 'zoom-in', name: 'Zoom In' },
    { value: 'pop-in', name: 'Pop In' },
    { value: 'flip-x-in', name: 'Flip X' },
    { value: 'flip-y-in', name: 'Flip Y' },
    { value: 'rotate-in', name: 'Rotate In' },
    { value: 'slide-up-in', name: 'Slide Up' },
    { value: 'slide-down-in', name: 'Slide Down' },
    { value: 'slide-left-in', name: 'Slide Left' },
    { value: 'slide-right-in', name: 'Slide Right' },
    { value: 'wipe-left-in', name: 'Wipe Left' },
    { value: 'wipe-right-in', name: 'Wipe Right' },
    { value: 'wipe-up-in', name: 'Wipe Up' },
    { value: 'wipe-down-in', name: 'Wipe Down' },
    { value: 'pixel-in', name: 'Pixel In' },
    { value: 'snake-in', name: 'Snake In' },
    { value: 'blur-in', name: 'Blur In' },
    { value: 'elastic-in', name: 'Elastic In' },
];

export const disappearAnimationOptions = [
    { value: 'none', name: 'None' },
    { value: 'fade-out', name: 'Fade Out' },
    { value: 'fade-up-out', name: 'Fade Up' },
    { value: 'fade-down-out', name: 'Fade Down' },
    { value: 'fade-left-out', name: 'Fade Left' },
    { value: 'fade-right-out', name: 'Fade Right' },
    { value: 'zoom-out', name: 'Zoom Out' },
    { value: 'pop-out', name: 'Pop Out' },
    { value: 'flip-x-out', name: 'Flip X' },
    { value: 'flip-y-out', name: 'Flip Y' },
    { value: 'rotate-out', name: 'Rotate Out' },
    { value: 'slide-up-out', name: 'Slide Up' },
    { value: 'slide-down-out', name: 'Slide Down' },
    { value: 'slide-left-out', name: 'Slide Left' },
    { value: 'slide-right-out', name: 'Slide Right' },
    { value: 'wipe-left-out', name: 'Wipe Left' },
    { value: 'wipe-right-out', name: 'Wipe Right' },
    { value: 'wipe-up-out', name: 'Wipe Up' },
    { value: 'wipe-down-out', name: 'Wipe Down' },
    { value: 'pixel-out', name: 'Pixel Out' },
    { value: 'snake-out', name: 'Snake Out' },
    { value: 'blur-out', name: 'Blur Out' },
    { value: 'elastic-out', name: 'Elastic Out' },
];

export const changeAnimationOptions = [
    { value: 'none', name: 'None' },
    { value: 'change-pulse', name: 'Pulse' },
    { value: 'change-pop', name: 'Pop' },
    { value: 'change-flip-x', name: 'Flip X' },
    { value: 'change-flip-y', name: 'Flip Y' },
    { value: 'change-tick-up', name: 'Tick Up' },
    { value: 'change-tick-down', name: 'Tick Down' },
    { value: 'change-slide-up', name: 'Slide Up' },
    { value: 'change-slide-down', name: 'Slide Down' },
    { value: 'change-spin', name: 'Spin' },
    { value: 'change-shake', name: 'Shake' },
    { value: 'change-flash', name: 'Flash' },
    { value: 'change-glow', name: 'Glow' },
    { value: 'change-explode', name: 'Explosion' },
    { value: 'change-compress', name: 'Compress' },
    { value: 'change-bounce', name: 'Bounce' },
];

export const viewAnimationOptions = [
    { value: 'none', name: 'None' },
    { value: 'border-flash', name: 'Border Flash' },
    { value: 'border-pulse', name: 'Border Pulse' },
    { value: 'border-glow', name: 'Border Glow' },
    { value: 'border-pop', name: 'Border Pop' },
    { value: 'border-sweep', name: 'Border Sweep' },
    { value: 'border-spin', name: 'Border Runner' },
    { value: 'twin-lights', name: 'Twin Lights' },
    { value: 'corner-chase', name: 'Corner Chase' },
    { value: 'comet-trace', name: 'Comet Trace' },
    { value: 'neon-trace', name: 'Neon Trace' },
    { value: 'scan-border', name: 'Scan Border' },
    { value: 'spotlight-orbit', name: 'Spotlight Trace' },
];

export const viewTriggerGroupOptions = [
    { value: 'any', name: 'Any Child Field' },
    { value: 'always-on', name: 'Always On' },
    { value: 'score-fields', name: 'Score Fields' },
    { value: 'current-score-fields', name: 'Current Score Fields' },
    { value: 'game-score-fields', name: 'Game Score Fields' },
    { value: 'player-name-fields', name: 'Player Name Fields' },
    { value: 'team-fields', name: 'Team Fields' },
    { value: 'status-fields', name: 'Status Fields' },
    { value: 'timeout-fields', name: 'Timeout Fields' },
    { value: 'service-fields', name: 'Service Fields' },
    { value: 'penalty-fields', name: 'Penalty Fields' },
    { value: 'image-fields', name: 'Image Fields' },
    { value: 'color-fields', name: 'Color Fields' },
    { value: 'custom', name: 'Custom Field List' },
];

export const viewTriggerScopeOptions = [
    { value: 'descendants', name: 'Any Descendant' },
    { value: 'direct-children', name: 'Direct Children Only' },
];

export const animationEasingOptions = [
    { value: 'ease', name: 'Ease' },
    { value: 'ease-in', name: 'Ease In' },
    { value: 'ease-out', name: 'Ease Out' },
    { value: 'ease-in-out', name: 'Ease In Out' },
    { value: 'linear', name: 'Linear' },
    { value: 'cubic-bezier(.2,.8,.2,1)', name: 'Soft Snap' },
    { value: 'cubic-bezier(.34,1.56,.64,1)', name: 'Overshoot' },
];
