export type GoogleFontOption = {
    family: string;
    category: 'sans-serif' | 'serif' | 'monospace' | 'display' | 'handwriting';
};

export const googleFontOptions: GoogleFontOption[] = [
    { family: 'ABeeZee', category: 'sans-serif' },
    { family: 'Abril Fatface', category: 'display' },
    { family: 'Acme', category: 'sans-serif' },
    { family: 'Alegreya', category: 'serif' },
    { family: 'Alegreya Sans', category: 'sans-serif' },
    { family: 'Alfa Slab One', category: 'display' },
    { family: 'Amaranth', category: 'sans-serif' },
    { family: 'Amatic SC', category: 'handwriting' },
    { family: 'Anonymous Pro', category: 'monospace' },
    { family: 'Anton', category: 'display' },
    { family: 'Archivo', category: 'sans-serif' },
    { family: 'Archivo Black', category: 'sans-serif' },
    { family: 'Arimo', category: 'sans-serif' },
    { family: 'Arvo', category: 'serif' },
    { family: 'Asap', category: 'sans-serif' },
    { family: 'Assistant', category: 'sans-serif' },
    { family: 'Audiowide', category: 'display' },
    { family: 'Balsamiq Sans', category: 'sans-serif' },
    { family: 'Barlow', category: 'sans-serif' },
    { family: 'Barlow Condensed', category: 'sans-serif' },
    { family: 'Barlow Semi Condensed', category: 'sans-serif' },
    { family: 'Bebas Neue', category: 'display' },
    { family: 'Bitter', category: 'serif' },
    { family: 'Black Ops One', category: 'display' },
    { family: 'Bowlby One SC', category: 'display' },
    { family: 'Bree Serif', category: 'serif' },
    { family: 'Bungee', category: 'display' },
    { family: 'Bungee Inline', category: 'display' },
    { family: 'Bungee Shade', category: 'display' },
    { family: 'Cabin', category: 'sans-serif' },
    { family: 'Cairo', category: 'sans-serif' },
    { family: 'Carter One', category: 'display' },
    { family: 'Catamaran', category: 'sans-serif' },
    { family: 'Caveat', category: 'handwriting' },
    { family: 'Chakra Petch', category: 'sans-serif' },
    { family: 'Changa', category: 'sans-serif' },
    { family: 'Changa One', category: 'display' },
    { family: 'Chivo', category: 'sans-serif' },
    { family: 'Cinzel', category: 'serif' },
    { family: 'Comfortaa', category: 'display' },
    { family: 'Cormorant', category: 'serif' },
    { family: 'Cormorant Garamond', category: 'serif' },
    { family: 'Courgette', category: 'handwriting' },
    { family: 'Crimson Text', category: 'serif' },
    { family: 'Cuprum', category: 'sans-serif' },
    { family: 'Dancing Script', category: 'handwriting' },
    { family: 'DM Sans', category: 'sans-serif' },
    { family: 'DM Serif Display', category: 'serif' },
    { family: 'Domine', category: 'serif' },
    { family: 'Dosis', category: 'sans-serif' },
    { family: 'EB Garamond', category: 'serif' },
    { family: 'Encode Sans', category: 'sans-serif' },
    { family: 'Exo', category: 'sans-serif' },
    { family: 'Exo 2', category: 'sans-serif' },
    { family: 'Fauna One', category: 'serif' },
    { family: 'Fira Code', category: 'monospace' },
    { family: 'Fira Sans', category: 'sans-serif' },
    { family: 'Fira Sans Condensed', category: 'sans-serif' },
    { family: 'Fjalla One', category: 'sans-serif' },
    { family: 'Francois One', category: 'sans-serif' },
    { family: 'Fredoka', category: 'sans-serif' },
    { family: 'Great Vibes', category: 'handwriting' },
    { family: 'Graduate', category: 'display' },
    { family: 'Heebo', category: 'sans-serif' },
    { family: 'Hind', category: 'sans-serif' },
    { family: 'IBM Plex Mono', category: 'monospace' },
    { family: 'IBM Plex Sans', category: 'sans-serif' },
    { family: 'IBM Plex Serif', category: 'serif' },
    { family: 'Inconsolata', category: 'monospace' },
    { family: 'Indie Flower', category: 'handwriting' },
    { family: 'Inter', category: 'sans-serif' },
    { family: 'Istok Web', category: 'sans-serif' },
    { family: 'JetBrains Mono', category: 'monospace' },
    { family: 'Josefin Sans', category: 'sans-serif' },
    { family: 'Josefin Slab', category: 'serif' },
    { family: 'Jost', category: 'sans-serif' },
    { family: 'Kalam', category: 'handwriting' },
    { family: 'Kanit', category: 'sans-serif' },
    { family: 'Karla', category: 'sans-serif' },
    { family: 'Khand', category: 'sans-serif' },
    { family: 'Laila', category: 'serif' },
    { family: 'Lato', category: 'sans-serif' },
    { family: 'League Gothic', category: 'sans-serif' },
    { family: 'League Spartan', category: 'sans-serif' },
    { family: 'Lexend', category: 'sans-serif' },
    { family: 'Libre Baskerville', category: 'serif' },
    { family: 'Libre Franklin', category: 'sans-serif' },
    { family: 'Lilita One', category: 'display' },
    { family: 'Lobster', category: 'display' },
    { family: 'Lora', category: 'serif' },
    { family: 'Mada', category: 'sans-serif' },
    { family: 'Mali', category: 'handwriting' },
    { family: 'Manrope', category: 'sans-serif' },
    { family: 'Martel', category: 'serif' },
    { family: 'Maven Pro', category: 'sans-serif' },
    { family: 'Merriweather', category: 'serif' },
    { family: 'Merriweather Sans', category: 'sans-serif' },
    { family: 'Montserrat', category: 'sans-serif' },
    { family: 'Montserrat Alternates', category: 'sans-serif' },
    { family: 'Monda', category: 'sans-serif' },
    { family: 'Mukta', category: 'sans-serif' },
    { family: 'Mulish', category: 'sans-serif' },
    { family: 'Nanum Gothic', category: 'sans-serif' },
    { family: 'Neuton', category: 'serif' },
    { family: 'News Cycle', category: 'sans-serif' },
    { family: 'Noto Sans', category: 'sans-serif' },
    { family: 'Noto Sans Display', category: 'sans-serif' },
    { family: 'Noto Sans JP', category: 'sans-serif' },
    { family: 'Noto Sans Mono', category: 'monospace' },
    { family: 'Noto Serif', category: 'serif' },
    { family: 'Noto Serif Display', category: 'serif' },
    { family: 'Nunito', category: 'sans-serif' },
    { family: 'Nunito Sans', category: 'sans-serif' },
    { family: 'Old Standard TT', category: 'serif' },
    { family: 'Open Sans', category: 'sans-serif' },
    { family: 'Orbitron', category: 'display' },
    { family: 'Oswald', category: 'sans-serif' },
    { family: 'Outfit', category: 'sans-serif' },
    { family: 'Overpass', category: 'sans-serif' },
    { family: 'Oxygen', category: 'sans-serif' },
    { family: 'Pacifico', category: 'handwriting' },
    { family: 'Passion One', category: 'display' },
    { family: 'Permanent Marker', category: 'handwriting' },
    { family: 'Philosopher', category: 'sans-serif' },
    { family: 'Play', category: 'sans-serif' },
    { family: 'Playfair Display', category: 'serif' },
    { family: 'Poiret One', category: 'display' },
    { family: 'Poppins', category: 'sans-serif' },
    { family: 'Prata', category: 'serif' },
    { family: 'Prompt', category: 'sans-serif' },
    { family: 'PT Mono', category: 'monospace' },
    { family: 'PT Sans', category: 'sans-serif' },
    { family: 'PT Serif', category: 'serif' },
    { family: 'Public Sans', category: 'sans-serif' },
    { family: 'Quantico', category: 'sans-serif' },
    { family: 'Quattrocento', category: 'serif' },
    { family: 'Questrial', category: 'sans-serif' },
    { family: 'Quicksand', category: 'sans-serif' },
    { family: 'Racing Sans One', category: 'display' },
    { family: 'Rajdhani', category: 'sans-serif' },
    { family: 'Raleway', category: 'sans-serif' },
    { family: 'Readex Pro', category: 'sans-serif' },
    { family: 'Red Hat Display', category: 'sans-serif' },
    { family: 'Red Hat Text', category: 'sans-serif' },
    { family: 'Righteous', category: 'display' },
    { family: 'Roboto', category: 'sans-serif' },
    { family: 'Roboto Condensed', category: 'sans-serif' },
    { family: 'Roboto Flex', category: 'sans-serif' },
    { family: 'Roboto Mono', category: 'monospace' },
    { family: 'Roboto Slab', category: 'serif' },
    { family: 'Rokkitt', category: 'serif' },
    { family: 'Rubik', category: 'sans-serif' },
    { family: 'Russo One', category: 'sans-serif' },
    { family: 'Saira', category: 'sans-serif' },
    { family: 'Saira Condensed', category: 'sans-serif' },
    { family: 'Saira Semi Condensed', category: 'sans-serif' },
    { family: 'Saira Stencil One', category: 'display' },
    { family: 'Satisfy', category: 'handwriting' },
    { family: 'Secular One', category: 'sans-serif' },
    { family: 'Shadows Into Light', category: 'handwriting' },
    { family: 'Signika', category: 'sans-serif' },
    { family: 'Signika Negative', category: 'sans-serif' },
    { family: 'Slabo 27px', category: 'serif' },
    { family: 'Source Code Pro', category: 'monospace' },
    { family: 'Source Sans 3', category: 'sans-serif' },
    { family: 'Source Serif 4', category: 'serif' },
    { family: 'Space Grotesk', category: 'sans-serif' },
    { family: 'Space Mono', category: 'monospace' },
    { family: 'Spectral', category: 'serif' },
    { family: 'Staatliches', category: 'display' },
    { family: 'Teko', category: 'sans-serif' },
    { family: 'Tinos', category: 'serif' },
    { family: 'Titillium Web', category: 'sans-serif' },
    { family: 'Tourney', category: 'display' },
    { family: 'Ubuntu', category: 'sans-serif' },
    { family: 'Ubuntu Condensed', category: 'sans-serif' },
    { family: 'Ubuntu Mono', category: 'monospace' },
    { family: 'Unica One', category: 'display' },
    { family: 'Varela Round', category: 'sans-serif' },
    { family: 'Vollkorn', category: 'serif' },
    { family: 'Wallpoet', category: 'display' },
    { family: 'Work Sans', category: 'sans-serif' },
    { family: 'Yanone Kaffeesatz', category: 'sans-serif' },
    { family: 'Yantramanav', category: 'sans-serif' },
    { family: 'Yeseva One', category: 'display' },
    { family: 'Ysabeau', category: 'sans-serif' },
    { family: 'Zilla Slab', category: 'serif' },
];
